name: build tools

on:
  push:
    branches: [main, develop]
    paths:
      - tools/**
      - tools-light/**

jobs:
  tools:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: tools
          file: tools/Dockerfile
          tags: borisdr/tools:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  light:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools-light
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v13
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: tools-light
          file: tools-light/Dockerfile
          tags: borisdr/tools-light:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}